# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\USER\Documents\CVDL\HW1\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1041, 553)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 231, 291))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.loadButton = QtWidgets.QPushButton(self.groupBox)
        self.loadButton.setGeometry(QtCore.QRect(10, 50, 201, 51))
        self.loadButton.setObjectName("loadButton")
        self.colorButton = QtWidgets.QPushButton(self.groupBox)
        self.colorButton.setGeometry(QtCore.QRect(10, 110, 201, 51))
        self.colorButton.setObjectName("colorButton")
        self.blendingButton = QtWidgets.QPushButton(self.groupBox)
        self.blendingButton.setGeometry(QtCore.QRect(10, 230, 201, 51))
        self.blendingButton.setObjectName("blendingButton")
        self.flippingButton = QtWidgets.QPushButton(self.groupBox)
        self.flippingButton.setGeometry(QtCore.QRect(10, 170, 201, 51))
        self.flippingButton.setObjectName("flippingButton")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 20, 311, 481))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 40, 291, 321))
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 40, 251, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit.setGeometry(QtCore.QRect(70, 30, 71, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 70, 71, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 110, 71, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 150, 71, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setGeometry(QtCore.QRect(150, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(150, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(150, 150, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.RSTButton = QtWidgets.QPushButton(self.groupBox_6)
        self.RSTButton.setGeometry(QtCore.QRect(10, 260, 271, 51))
        self.RSTButton.setObjectName("RSTButton")
        self.ptButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ptButton.setGeometry(QtCore.QRect(20, 390, 271, 51))
        self.ptButton.setObjectName("ptButton")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(530, 510, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(260, 30, 181, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gtButton = QtWidgets.QPushButton(self.groupBox_5)
        self.gtButton.setGeometry(QtCore.QRect(20, 30, 151, 51))
        self.gtButton.setObjectName("gtButton")
        self.ltButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.ltButton_3.setGeometry(QtCore.QRect(20, 100, 151, 51))
        self.ltButton_3.setObjectName("ltButton_3")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(260, 220, 181, 321))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gaussianButton = QtWidgets.QPushButton(self.groupBox_8)
        self.gaussianButton.setGeometry(QtCore.QRect(20, 30, 151, 51))
        self.gaussianButton.setObjectName("gaussianButton")
        self.sebelxButton = QtWidgets.QPushButton(self.groupBox_8)
        self.sebelxButton.setGeometry(QtCore.QRect(20, 100, 151, 51))
        self.sebelxButton.setObjectName("sebelxButton")
        self.sebelyButton = QtWidgets.QPushButton(self.groupBox_8)
        self.sebelyButton.setGeometry(QtCore.QRect(20, 160, 151, 51))
        self.sebelyButton.setObjectName("sebelyButton")
        self.magButton = QtWidgets.QPushButton(self.groupBox_8)
        self.magButton.setGeometry(QtCore.QRect(20, 230, 151, 51))
        self.magButton.setObjectName("magButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(770, 40, 251, 461))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.showButton = QtWidgets.QPushButton(self.groupBox_2)
        self.showButton.setGeometry(QtCore.QRect(10, 50, 231, 51))
        self.showButton.setObjectName("showButton")
        self.paraButton = QtWidgets.QPushButton(self.groupBox_2)
        self.paraButton.setGeometry(QtCore.QRect(10, 110, 231, 51))
        self.paraButton.setObjectName("paraButton")
        self.resultButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.resultButton_2.setGeometry(QtCore.QRect(10, 230, 231, 51))
        self.resultButton_2.setObjectName("resultButton_2")
        self.epochButton = QtWidgets.QPushButton(self.groupBox_2)
        self.epochButton.setGeometry(QtCore.QRect(10, 170, 231, 51))
        self.epochButton.setObjectName("epochButton")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 290, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_index = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_index.setGeometry(QtCore.QRect(140, 290, 101, 31))
        self.lineEdit_index.setObjectName("lineEdit_index")
        self.inferenceButton = QtWidgets.QPushButton(self.groupBox_2)
        self.inferenceButton.setGeometry(QtCore.QRect(10, 330, 231, 51))
        self.inferenceButton.setObjectName("inferenceButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "1. Image Processing"))
        self.loadButton.setText(_translate("Form", "1.1 Load Image"))
        self.colorButton.setText(_translate("Form", "1.2 Color Conversion "))
        self.blendingButton.setText(_translate("Form", "1.4 Blending"))
        self.flippingButton.setText(_translate("Form", "1.3 Image Flipping"))
        self.groupBox_3.setTitle(_translate("Form", "3. Image Transformation"))
        self.groupBox_6.setTitle(_translate("Form", "3.1 Rot, Scale, Translate"))
        self.groupBox_7.setTitle(_translate("Form", "Parameter"))
        self.label_3.setText(_translate("Form", "Tx："))
        self.label_4.setText(_translate("Form", "Ty："))
        self.label_5.setText(_translate("Form", "Scale："))
        self.label_2.setText(_translate("Form", "Angle："))
        self.label_6.setText(_translate("Form", "deg"))
        self.label_7.setText(_translate("Form", "pixel"))
        self.label_8.setText(_translate("Form", "pixel"))
        self.RSTButton.setText(_translate("Form", "3.1 Rot, Scale, Translate"))
        self.ptButton.setText(_translate("Form", "3.2 Perspective transform "))
        self.groupBox_5.setTitle(_translate("Form", "2. Adaptive Threshold "))
        self.gtButton.setText(_translate("Form", "2.1 Global Threshold "))
        self.ltButton_3.setText(_translate("Form", "2.1 Local Threshold"))
        self.groupBox_8.setTitle(_translate("Form", "3. Convolution"))
        self.gaussianButton.setText(_translate("Form", "4.1 Gaussian"))
        self.sebelxButton.setText(_translate("Form", "4.2 Sobel X"))
        self.sebelyButton.setText(_translate("Form", "4.3 Sobel Y"))
        self.magButton.setText(_translate("Form", "4.4 Magnitude"))
        self.groupBox_2.setTitle(_translate("Form", "5. MNIST Using LeNet5"))
        self.showButton.setText(_translate("Form", "5.1 Show train Image"))
        self.paraButton.setText(_translate("Form", "5.2 Show hyperparameters"))
        self.resultButton_2.setText(_translate("Form", "5.4 Show Training Result"))
        self.epochButton.setText(_translate("Form", "5.3 Train 1Epoch"))
        self.label_9.setText(_translate("Form", "Test Image Index："))
        self.inferenceButton.setText(_translate("Form", "5.5 Inference"))
